### ISSUE TITLE
SwiperFlatList index>0,don't touch to next page

### ISSUE THREAD

**Issue by mrstluo** [gusgard/react-native-swiper-flatlist#83]
Hello! I found a bug

this code is work good.

```javascript
  renderPage() {
    return (
      <View style={styles.container}>
        <SwiperFlatList  index={1} >
          <View style={[styles.child, { backgroundColor: 'tomato' }]}>
            <Text style={styles.text}>1</Text>
          </View>
          <View style={[styles.child, { backgroundColor: 'thistle' }]}>
            <Text style={styles.text}>2</Text>
          </View>
          <View style={[styles.child, { backgroundColor: 'skyblue' }]}>
            <Text style={styles.text}>3</Text>
          </View>
          <View style={[styles.child, { backgroundColor: 'teal' }]}>
            <Text style={styles.text}>4</Text>
          </View>
        </SwiperFlatList>
      </View>
    )
  }
```

but this code ,if index=0,work good,if index>0, don't touch to next page

```javascript
  constructor(props) {
        super(props);

        const pages = [];
      for (let i = 0; i < 50; i++) {
        pages.push(i);
      }

      this.state = {
            data: pages
        };

    }



  renderPage() {
    return (
      <View style={styles.container}>
        <SwiperFlatList  index={1} >
          {this.state.data.map((p) => {
            return(
              <View key={"SwipeRender-slide#" +p} style={[styles.child, { backgroundColor: 'tomato' }]}>
            <Text style={styles.text}>{p}</Text>
          </View>
            )
          })}
        </SwiperFlatList>
      </View>
    )
  }
```
```css
const styles = StyleSheet.create({
  viewPager: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  child: {
    height: height * 0.5,
    width,
    justifyContent: 'center',
  },
  text: {
    fontSize: 28,
    textAlign: 'center',
  },
});
```

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 4.67 GB / 15.88 GB
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Users\luoyahu\AppData\Roaming\npm\yarn.CMD
    npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: 4.9.4 - F:\tools\watchman\watchman.EXE
  SDKs:
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
